// SEO meta configuration for all admin panel routes in PVJ
// Update this file to change admin page titles and descriptions centrally

export const ADMIN_SEO_META = {
    "/admin": { title: "Admin Panel - PVJ", description: "PVJ Admin Dashboard and Management Panel." },
    "/admin/dashboard": { title: "Dashboard - Admin | PVJ", description: "Overview of sales, users, and platform analytics for PVJ admins." },
    "/admin/orders/orders-management": { title: "Orders Management - Admin | PVJ", description: "Manage all customer orders in the PVJ admin panel." },
    "/admin/orders/video-consultations": { title: "Video Consultations - Admin | PVJ", description: "Manage and track video consultations booked by users." },
    "/admin/orders/cart-management": { title: "Cart Management - Admin | PVJ", description: "Monitor and manage user carts in the PVJ admin panel." },
    "/admin/products/listing": { title: "Product Listing - Admin | PVJ", description: "View and manage all products in the PVJ inventory." },

    "/admin/products/wishlist-monitoring": { title: "Wishlist Monitoring - Admin | PVJ", description: "Monitor user wishlists in the PVJ admin panel." },
    "/admin/products/certificate-management": { title: "Certificate Management - Admin | PVJ", description: "Manage product certificates and authenticity documents." },
    "/admin/products/product-catelog": { title: "Product Catalog - Admin | PVJ", description: "Manage product categories, subcategories, and attributes." },
    "/admin/products/gemstone-catalog": { title: "Gemstone Catalog - Admin | PVJ", description: "Manage gemstone catalog and attributes." },
    "/admin/carts-discounts/cart-and-discount": { title: "Cart & Discount - Admin | PVJ", description: "Manage cart rules and discount offers for PVJ." },
    "/admin/carts-discounts/discount-management": { title: "Discount Management - Admin | PVJ", description: "Create and manage discount codes and offers." },
    "/admin/shipping/pincode-management": { title: "Pincode Management - Admin | PVJ", description: "Manage serviceable pincodes for shipping." },
    "/admin/shipping/product-delivery": { title: "Product Delivery - Admin | PVJ", description: "Track and manage product deliveries." },
    "/admin/user-management/user-account": { title: "User Account Management - Admin | PVJ", description: "Manage user accounts and permissions." },
    "/admin/user-management/support-ticket": { title: "Support Ticket Management - Admin | PVJ", description: "Handle and resolve user support tickets." },
    "/admin/user-management/contact-management": { title: "Contact Management - Admin | PVJ", description: "Manage and respond to customer contact messages." },
    "/admin/user-management/elite-member-management": { title: "Elite Member Management - Admin | PVJ", description: "Manage elite member subscriptions and memberships." },
    "/admin/marketing/blog-guide": { title: "Blog Guide - Admin | PVJ", description: "Manage blog content and guides for PVJ." },
    "/admin/marketing/email-automation": { title: "Email Automation - Admin | PVJ", description: "Configure and manage email automation campaigns." },
    "/admin/marketing/review-rating": { title: "Review & Rating - Admin | PVJ", description: "Monitor and manage product reviews and ratings." },
    "/admin/marketing/most-selling-products": { title: "Most Selling Products - Admin | PVJ", description: "View analytics and insights for top-selling products." },
    "/admin/marketing/most-selling-locations": { title: "Most Selling Locations - Admin | PVJ", description: "View analytics and insights for top-selling locations." },
    "/admin/marketing/facebook-pixel": { title: "Facebook Pixel - Admin | PVJ", description: "Configure and manage Facebook Pixel tracking." },

    "/admin/gold-silver/rate-prediction": { title: "Gold & Silver Rate Prediction - Admin | PVJ", description: "Manage rate prediction tools for gold and silver." },
    "/admin/gold-silver/rate-update": { title: "Gold & Silver Rate Update - Admin | PVJ", description: "Update and manage gold and silver rates." },
    "/admin/gold-silver/prediction-management": { title: "Prediction Management - Admin | PVJ", description: "Manage gold and silver price predictions, forecast periods, and market analysis for PVJ." },
    "/admin/cms/cms-tracker": { title: "CMS Tracker - Admin | PVJ", description: "Track and manage CMS content for PVJ." },
    "/admin/cms/blog-guide": { title: "Blog Guide - Admin | PVJ", description: "Manage blog content and guides for PVJ." },
    "/admin/cms/social-links": { title: "Social Links - Admin | PVJ", description: "Manage social media links for PVJ." },
    "/admin/cms/gallery-management": { title: "Gallery Management - Admin | PVJ", description: "Manage image gallery for PVJ site." },
    "gallery": { title: "Gallery Management - Admin | PVJ", description: "Manage image gallery for PVJ site." },
    "/admin/cms/offer-carousel": { title: "Offer Carousel - Admin | PVJ", description: "Manage offer carousel banners and promotions." },
    "offer-carousel": { title: "Offer Carousel - Admin | PVJ", description: "Manage offer carousel banners and promotions." },
    "/admin/cms/chatbot-qa": { title: "Chatbot Q&A - Admin | PVJ", description: "Manage chatbot questions and answers." },
    "chatbot-qa": { title: "Chatbot Q&A - Admin | PVJ", description: "Manage chatbot questions and answers." },
    "/admin/cms/hero-banner": { title: "Hero Banner - Admin | PVJ", description: "Manage homepage hero banners." },
    "/admin/cms/featured-images": { title: "Featured Images - Admin | PVJ", description: "Manage featured images for PVJ site." },
    "/admin/cms/pvj-prediction": { title: "PVJ Prediction - Admin | PVJ", description: "Manage PVJ prediction content." },
    "/admin/cms/second-category": { title: "Second Feature Category - Admin | PVJ", description: "Manage secondary featured categories." },
    "/admin/cms/insta-images": { title: "Instagram Images - Admin | PVJ", description: "Manage Instagram images for PVJ." },
    "/admin/cms/about-us": { title: "About Us - Admin | PVJ", description: "Manage About Us page content." },
    "/admin/cms/faq-management": { title: "FAQ Management - Admin | PVJ", description: "Manage frequently asked questions." },
    "/admin/cms/return-policy": { title: "Return Policy - Admin | PVJ", description: "Manage return and cancellation policy content." },
    "/admin/cms/privacy-policy": { title: "Privacy Policy - Admin | PVJ", description: "Manage privacy policy content." },
    "/admin/cms/terms-conditions": { title: "Terms & Conditions - Admin | PVJ", description: "Manage terms and conditions content." },
    "/admin/cms/shipping-policy": { title: "Shipping Policy - Admin | PVJ", description: "Manage shipping policy content." },
    "/admin/cms/shop-banner": { title: "Shop Banner - Admin | PVJ", description: "Manage shop page banners." },
    "/admin/cms/client-diary": { title: "Client Diary - Admin | PVJ", description: "Manage client diary and testimonials." },
    "/admin/cms/product-banner": { title: "Product Banner - Admin | PVJ", description: "Manage product page banners." },
    "/admin/digital-gold": { title: "Digital Gold Overview - Admin | PVJ", description: "Overview and management of digital gold products." },
    "/admin/custom-jewelry": { title: "Custom Jewelry - Admin | PVJ", description: "Manage custom jewelry requests and orders." },
    "/admin/plan-controller-center": { title: "11 + 1 Plan - Admin | PVJ", description: "Manage 11 + 1 plan controller center for PVJ." },
    "/admin/chatbot-qa-management": { title: "Chatbot Q&A Management - Admin | PVJ", description: "Manage chatbot questions and answers." },
    "/admin/reset-password": { title: "Reset Password - Admin | PVJ", description: "Reset your admin password for PVJ." },
    "*": { title: "Page Not Found - Admin | PVJ", description: "The admin page you're looking for doesn't exist. Navigate back to the admin dashboard or explore other admin pages." }
}; 